stages:
 - validate
 - snyk
 - plan
 - apply

image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - export TF_PASSWORD=${GITLAB_ACCESS_KEY}
  - export TF_USERNAME=${TF_USERNAME}
  - export PROJECT_ID=${PROJECT_ID}
  - export TF_ADDRESS=${TF_ADDRESS}
  - export SNYK_TOKEN=${SNYK_TOKEN}
  - echo $TF_ADDRESS
  - rm -rf .terraform
  - terraform --version
  - terraform init -backend-config=address=${TF_ADDRESS} -backend-config=lock_address=${TF_ADDRESS}/lock -backend-config=unlock_address=${TF_ADDRESS}/lock -backend-config=username=${TF_USERNAME} -backend-config=password=${TF_PASSWORD} -backend-config=lock_method=POST -backend-config=unlock_method=DELETE -backend-config=retry_wait_min=5

validate:
  stage: validate
  script:
    - terraform validate
snyk:
  stage: snyk
  script:
    - snyk iac test --severity-threshold=medium
plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile
apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual
